//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować niewłaściwe zachowanie i zostaną utracone
//     w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFKantor
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDetails", Namespace="http://schemas.datacontract.org/2004/07/KantorWCF")]
    public partial class UserDetails : object
    {
        
        private string UserEmailField;
        
        private string UserNameField;
        
        private string UserPasswordField;
        
        private string UserSurnameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail
        {
            get
            {
                return this.UserEmailField;
            }
            set
            {
                this.UserEmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPassword
        {
            get
            {
                return this.UserPasswordField;
            }
            set
            {
                this.UserPasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserSurname
        {
            get
            {
                return this.UserSurnameField;
            }
            set
            {
                this.UserSurnameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountDetails", Namespace="http://schemas.datacontract.org/2004/07/KantorWCF")]
    public partial class AccountDetails : object
    {
        
        private decimal AmountField;
        
        private string CurrencyField;
        
        private int UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferHistory", Namespace="http://schemas.datacontract.org/2004/07/KantorWCF")]
    public partial class TransferHistory : object
    {
        
        private decimal AmountField;
        
        private string CurrencyField;
        
        private System.DateTime DateField;
        
        private string TypeField;
        
        private int UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transactions", Namespace="http://schemas.datacontract.org/2004/07/KantorWCF")]
    public partial class Transactions : object
    {
        
        private string CurrencyField;
        
        private System.DateTime DateField;
        
        private decimal ExchangeField;
        
        private decimal PlnField;
        
        private decimal ScoreField;
        
        private string TypeField;
        
        private int UserIDField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Currency
        {
            get
            {
                return this.CurrencyField;
            }
            set
            {
                this.CurrencyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Exchange
        {
            get
            {
                return this.ExchangeField;
            }
            set
            {
                this.ExchangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Pln
        {
            get
            {
                return this.PlnField;
            }
            set
            {
                this.PlnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Score
        {
            get
            {
                return this.ScoreField;
            }
            set
            {
                this.ScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID
        {
            get
            {
                return this.UserIDField;
            }
            set
            {
                this.UserIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFKantor.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckArchiveRate", ReplyAction="http://tempuri.org/IService1/CheckArchiveRateResponse")]
        string CheckArchiveRate(string date, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckArchiveRate", ReplyAction="http://tempuri.org/IService1/CheckArchiveRateResponse")]
        System.Threading.Tasks.Task<string> CheckArchiveRateAsync(string date, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MakeExchangeSell", ReplyAction="http://tempuri.org/IService1/MakeExchangeSellResponse")]
        double MakeExchangeSell(double money, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MakeExchangeSell", ReplyAction="http://tempuri.org/IService1/MakeExchangeSellResponse")]
        System.Threading.Tasks.Task<double> MakeExchangeSellAsync(double money, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MakeExchangeBuy", ReplyAction="http://tempuri.org/IService1/MakeExchangeBuyResponse")]
        double MakeExchangeBuy(double money, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/MakeExchangeBuy", ReplyAction="http://tempuri.org/IService1/MakeExchangeBuyResponse")]
        System.Threading.Tasks.Task<double> MakeExchangeBuyAsync(double money, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        string GetExchangeRate(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExchangeRate", ReplyAction="http://tempuri.org/IService1/GetExchangeRateResponse")]
        System.Threading.Tasks.Task<string> GetExchangeRateAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RejestracjaUzytkownika", ReplyAction="http://tempuri.org/IService1/RejestracjaUzytkownikaResponse")]
        string RejestracjaUzytkownika(WCFKantor.UserDetails userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RejestracjaUzytkownika", ReplyAction="http://tempuri.org/IService1/RejestracjaUzytkownikaResponse")]
        System.Threading.Tasks.Task<string> RejestracjaUzytkownikaAsync(WCFKantor.UserDetails userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogowanieUzytkownika", ReplyAction="http://tempuri.org/IService1/LogowanieUzytkownikaResponse")]
        bool LogowanieUzytkownika(WCFKantor.UserDetails userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LogowanieUzytkownika", ReplyAction="http://tempuri.org/IService1/LogowanieUzytkownikaResponse")]
        System.Threading.Tasks.Task<bool> LogowanieUzytkownikaAsync(WCFKantor.UserDetails userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PobierzDane", ReplyAction="http://tempuri.org/IService1/PobierzDaneResponse")]
        System.Collections.Generic.Dictionary<string, string> PobierzDane(WCFKantor.UserDetails userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/PobierzDane", ReplyAction="http://tempuri.org/IService1/PobierzDaneResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> PobierzDaneAsync(WCFKantor.UserDetails userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStanKonta", ReplyAction="http://tempuri.org/IService1/GetStanKontaResponse")]
        System.Collections.Generic.Dictionary<string, decimal> GetStanKonta(WCFKantor.UserDetails userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStanKonta", ReplyAction="http://tempuri.org/IService1/GetStanKontaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, decimal>> GetStanKontaAsync(WCFKantor.UserDetails userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStanKonta", ReplyAction="http://tempuri.org/IService1/UpdateStanKontaResponse")]
        string UpdateStanKonta(WCFKantor.AccountDetails account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateStanKonta", ReplyAction="http://tempuri.org/IService1/UpdateStanKontaResponse")]
        System.Threading.Tasks.Task<string> UpdateStanKontaAsync(WCFKantor.AccountDetails account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpgradeStanKonta", ReplyAction="http://tempuri.org/IService1/UpgradeStanKontaResponse")]
        string UpgradeStanKonta(WCFKantor.AccountDetails account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpgradeStanKonta", ReplyAction="http://tempuri.org/IService1/UpgradeStanKontaResponse")]
        System.Threading.Tasks.Task<string> UpgradeStanKontaAsync(WCFKantor.AccountDetails account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHistoriaPrzelewow", ReplyAction="http://tempuri.org/IService1/GetHistoriaPrzelewowResponse")]
        string GetHistoriaPrzelewow(WCFKantor.TransferHistory history);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetHistoriaPrzelewow", ReplyAction="http://tempuri.org/IService1/GetHistoriaPrzelewowResponse")]
        System.Threading.Tasks.Task<string> GetHistoriaPrzelewowAsync(WCFKantor.TransferHistory history);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetHistoriaPrzelewow", ReplyAction="http://tempuri.org/IService1/SetHistoriaPrzelewowResponse")]
        string SetHistoriaPrzelewow(WCFKantor.TransferHistory history);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetHistoriaPrzelewow", ReplyAction="http://tempuri.org/IService1/SetHistoriaPrzelewowResponse")]
        System.Threading.Tasks.Task<string> SetHistoriaPrzelewowAsync(WCFKantor.TransferHistory history);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTransakcje", ReplyAction="http://tempuri.org/IService1/GetTransakcjeResponse")]
        string GetTransakcje(WCFKantor.Transactions transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetTransakcje", ReplyAction="http://tempuri.org/IService1/GetTransakcjeResponse")]
        System.Threading.Tasks.Task<string> GetTransakcjeAsync(WCFKantor.Transactions transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetTransakcje", ReplyAction="http://tempuri.org/IService1/SetTransakcjeResponse")]
        string SetTransakcje(WCFKantor.Transactions transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SetTransakcje", ReplyAction="http://tempuri.org/IService1/SetTransakcjeResponse")]
        System.Threading.Tasks.Task<string> SetTransakcjeAsync(WCFKantor.Transactions transaction);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAccount", ReplyAction="http://tempuri.org/IService1/DeleteAccountResponse")]
        string DeleteAccount(WCFKantor.UserDetails userInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAccount", ReplyAction="http://tempuri.org/IService1/DeleteAccountResponse")]
        System.Threading.Tasks.Task<string> DeleteAccountAsync(WCFKantor.UserDetails userInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IService1Channel : WCFKantor.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCFKantor.IService1>, WCFKantor.IService1
    {
        
        /// <summary>
        /// Wdróż tę metodę częściową, aby skonfigurować punkt końcowy usługi.
        /// </summary>
        /// <param name="serviceEndpoint">Punkt końcowy do skonfigurowania</param>
        /// <param name="clientCredentials">Poświadczenia klienta</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string CheckArchiveRate(string date, string value)
        {
            return base.Channel.CheckArchiveRate(date, value);
        }
        
        public System.Threading.Tasks.Task<string> CheckArchiveRateAsync(string date, string value)
        {
            return base.Channel.CheckArchiveRateAsync(date, value);
        }
        
        public double MakeExchangeSell(double money, string value)
        {
            return base.Channel.MakeExchangeSell(money, value);
        }
        
        public System.Threading.Tasks.Task<double> MakeExchangeSellAsync(double money, string value)
        {
            return base.Channel.MakeExchangeSellAsync(money, value);
        }
        
        public double MakeExchangeBuy(double money, string value)
        {
            return base.Channel.MakeExchangeBuy(money, value);
        }
        
        public System.Threading.Tasks.Task<double> MakeExchangeBuyAsync(double money, string value)
        {
            return base.Channel.MakeExchangeBuyAsync(money, value);
        }
        
        public string GetExchangeRate(string value)
        {
            return base.Channel.GetExchangeRate(value);
        }
        
        public System.Threading.Tasks.Task<string> GetExchangeRateAsync(string value)
        {
            return base.Channel.GetExchangeRateAsync(value);
        }
        
        public string RejestracjaUzytkownika(WCFKantor.UserDetails userInfo)
        {
            return base.Channel.RejestracjaUzytkownika(userInfo);
        }
        
        public System.Threading.Tasks.Task<string> RejestracjaUzytkownikaAsync(WCFKantor.UserDetails userInfo)
        {
            return base.Channel.RejestracjaUzytkownikaAsync(userInfo);
        }
        
        public bool LogowanieUzytkownika(WCFKantor.UserDetails userInfo)
        {
            return base.Channel.LogowanieUzytkownika(userInfo);
        }
        
        public System.Threading.Tasks.Task<bool> LogowanieUzytkownikaAsync(WCFKantor.UserDetails userInfo)
        {
            return base.Channel.LogowanieUzytkownikaAsync(userInfo);
        }
        
        public System.Collections.Generic.Dictionary<string, string> PobierzDane(WCFKantor.UserDetails userInfo)
        {
            return base.Channel.PobierzDane(userInfo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> PobierzDaneAsync(WCFKantor.UserDetails userInfo)
        {
            return base.Channel.PobierzDaneAsync(userInfo);
        }
        
        public System.Collections.Generic.Dictionary<string, decimal> GetStanKonta(WCFKantor.UserDetails userInfo)
        {
            return base.Channel.GetStanKonta(userInfo);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, decimal>> GetStanKontaAsync(WCFKantor.UserDetails userInfo)
        {
            return base.Channel.GetStanKontaAsync(userInfo);
        }
        
        public string UpdateStanKonta(WCFKantor.AccountDetails account)
        {
            return base.Channel.UpdateStanKonta(account);
        }
        
        public System.Threading.Tasks.Task<string> UpdateStanKontaAsync(WCFKantor.AccountDetails account)
        {
            return base.Channel.UpdateStanKontaAsync(account);
        }
        
        public string UpgradeStanKonta(WCFKantor.AccountDetails account)
        {
            return base.Channel.UpgradeStanKonta(account);
        }
        
        public System.Threading.Tasks.Task<string> UpgradeStanKontaAsync(WCFKantor.AccountDetails account)
        {
            return base.Channel.UpgradeStanKontaAsync(account);
        }
        
        public string GetHistoriaPrzelewow(WCFKantor.TransferHistory history)
        {
            return base.Channel.GetHistoriaPrzelewow(history);
        }
        
        public System.Threading.Tasks.Task<string> GetHistoriaPrzelewowAsync(WCFKantor.TransferHistory history)
        {
            return base.Channel.GetHistoriaPrzelewowAsync(history);
        }
        
        public string SetHistoriaPrzelewow(WCFKantor.TransferHistory history)
        {
            return base.Channel.SetHistoriaPrzelewow(history);
        }
        
        public System.Threading.Tasks.Task<string> SetHistoriaPrzelewowAsync(WCFKantor.TransferHistory history)
        {
            return base.Channel.SetHistoriaPrzelewowAsync(history);
        }
        
        public string GetTransakcje(WCFKantor.Transactions transaction)
        {
            return base.Channel.GetTransakcje(transaction);
        }
        
        public System.Threading.Tasks.Task<string> GetTransakcjeAsync(WCFKantor.Transactions transaction)
        {
            return base.Channel.GetTransakcjeAsync(transaction);
        }
        
        public string SetTransakcje(WCFKantor.Transactions transaction)
        {
            return base.Channel.SetTransakcje(transaction);
        }
        
        public System.Threading.Tasks.Task<string> SetTransakcjeAsync(WCFKantor.Transactions transaction)
        {
            return base.Channel.SetTransakcjeAsync(transaction);
        }
        
        public string DeleteAccount(WCFKantor.UserDetails userInfo)
        {
            return base.Channel.DeleteAccount(userInfo);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAccountAsync(WCFKantor.UserDetails userInfo)
        {
            return base.Channel.DeleteAccountAsync(userInfo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.0.100:49393/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
